site_name: Python Support Scripts Documentation
site_description: Documentation for DTU Python Support installation scripts
site_url: https://philipnickel.github.io/pythonsupport-scripts

docs_dir: .
site_dir: ../site

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

nav:
  - Home: index.md
  - MacOS:
    - Components:
      - Overview: macos/components/index.md
      - Diagnostics: macos/components/diagnostics.md
      - Homebrew: macos/components/homebrew.md
      - LaTeX: macos/components/latex.md
      - Python: macos/components/python.md
      - VSCode: macos/components/vscode.md
      - Utilities: macos/components/utilities.md
    - Complete Installations:
      - Overview: macos/orchestrators/index.md
  - Windows:
    - Overview: windows/index.md
    - Components:
      - Overview: windows/components/index.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences