name: Constructor Build and Test

on:
  workflow_dispatch:
  push:
    branches: [constructor-pkg-installer]
    paths: 
      - 'MacOS/constructor_installer/**'
      - '.github/workflows/constructor-build-and-test.yml'

env:
  PYTHON_VERSION_PS: "3.11"

jobs:
  build-pkg:
    name: Build Constructor PKG
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ env.PYTHON_VERSION_PS }}
          channels: conda-forge
          channel-priority: strict

      - name: Install Constructor
        shell: bash -el {0}
        run: |
          conda install constructor -y
          constructor --version

      - name: Build PKG
        shell: bash -el {0}
        working-directory: MacOS/constructor_installer/python_stack
        run: |
          echo "Building constructor PKG..."
          ./build.sh

      - name: Upload PKG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dtu-python-stack-pkg
          path: MacOS/constructor_installer/python_stack/builds/*.pkg
          retention-days: 1

  test-pkg:
    name: Test PKG Installation
    runs-on: macos-latest
    needs: build-pkg
    steps:
      - name: Download PKG Artifact
        uses: actions/download-artifact@v4
        with:
          name: dtu-python-stack-pkg
          path: ./

      - name: Test PKG Installation
        run: |
          # Find the PKG file
          PKG_FILE=$(find . -name "*.pkg" -type f | head -1)
          if [[ -z "$PKG_FILE" ]]; then
            echo "❌ No PKG file found"
            exit 1
          fi
          
          echo "✅ Testing PKG: $PKG_FILE"
          echo "📁 Size: $(du -h "$PKG_FILE" | cut -f1)"
          
          # Install the PKG (without sudo as we determined that works)
          echo ""
          echo "=== Installing PKG ==="
          CONDA_VERBOSITY=3 installer -verbose -pkg "$PKG_FILE" -target CurrentUserHomeDirectory -dumplog
          
          echo ""
          echo "=== Post-Installation Environment Setup ==="
          
          # Give installation a moment to complete
          sleep 5
          
          # Update shell environment (like existing workflows)
          hash -r 2>/dev/null || true
          
          echo "=== Testing Default Python Environment ==="
          
          # Test if the PKG installer set up the environment correctly
          # We should be able to just use python3 directly
          
          # Test Python version - check both default and constructor installation
          echo "Testing Python installations..."
          echo "Default Python3: $(python3 --version) at $(which python3)"
          
          # Check if constructor installed Python is available
          CONSTRUCTOR_PYTHON_FOUND=false
          for python_path in "$HOME/miniconda3/bin/python3" "$HOME/anaconda3/bin/python3" "/opt/miniconda3/bin/python3"; do
            if [ -f "$python_path" ]; then
              PYTHON_VERSION=$("$python_path" --version 2>/dev/null | cut -d " " -f 2)
              echo "Constructor Python: $PYTHON_VERSION at $python_path"
              if [[ "$PYTHON_VERSION" == "${{ env.PYTHON_VERSION_PS }}"* ]]; then
                echo "✅ Found constructor Python 3.11 installation"
                CONSTRUCTOR_PYTHON="$python_path"
                CONSTRUCTOR_PYTHON_FOUND=true
                break
              fi
            fi
          done
          
          if [ "$CONSTRUCTOR_PYTHON_FOUND" = false ]; then
            echo "❌ Could not find constructor Python 3.11 installation"
            echo "This means the PKG didn't install Python where expected"
            exit 1
          fi
          
          # Test conda (optional - should be available but not required for package imports)
          if command -v conda >/dev/null 2>&1; then
            echo "✅ Conda: $(conda --version)"
            echo "  Location: $(which conda)"
          else
            echo "ℹ️  Conda: Not in PATH (this is OK if packages still import)"
          fi
          
          # Test package imports with constructor Python - THE CRITICAL TEST!
          echo ""
          echo "=== Testing Package Imports ==="
          echo "Using constructor Python: $CONSTRUCTOR_PYTHON"
          
          if "$CONSTRUCTOR_PYTHON" -c "import pandas, scipy, statsmodels, uncertainties, dtumathtools; print('✅ All packages work')"; then
            echo "✅ All packages imported successfully with constructor Python"
          else
            echo "❌ Package imports failed with constructor Python"
            exit 1
          fi
          
          echo ""
          echo "🎉 CONSTRUCTOR PKG TEST: SUCCESS!"
          echo "✅ PKG installs correctly"
          echo "✅ Python environment works" 
          echo "✅ All packages import successfully"
          echo "✅ Constructor PKG approach is viable!"