defaults: 
  run: 
    shell: bash -l {0}
# This is a basic workflow to help you get started with Actions

name: Verification of installation scripts 

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_macos_intel:
    runs-on: macos-12
    steps:
      - name: python pre-check
        run: |
          # python version
          python3 --version 
          which python3 
      
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run MacOS installation script 
        env: 
          REMOTE_PS: ${{ github.repository_owner }}
          BRANCH_PS: ${{ github.head_ref }}
          
        run: |
          echo "Running script from remote $REMOTE_PS on branch $BRANCH_PS"
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/$REMOTE_PS/pythonsupport-scripts/$BRANCH_PS/AutoInstallMacOS_main.sh)"
      
      - name: Verification 
        run: |
          # check python version
          python3 --version
          which python3
          # vs code
          code --version
          # conda 
          conda --version
          which conda
          # packages 
          python3 -c "import dtumathtools; import uncertainties; print('Packages imported successfully')"
      
