name: MacOS Orchestrators Tests

defaults:
  run:
    shell: bash -l {0}

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'MacOS/Components/**'
      - '.github/workflows/mac_orchestrators.yml'
  push:
    branches: [ "mac-scripts-components" ]
    paths:
      - 'MacOS/Components/**'
      - '.github/workflows/mac_orchestrators.yml'
  workflow_dispatch:

env:
  PYTHON_VERSION_PS: "3.11"

jobs:
  test-first-year-orchestrator:
    name: Test First Year Orchestrator
    runs-on: macos-latest
    
    steps:
      - name: Clean System
        run: |
          # Remove existing installations
          if command -v brew > /dev/null; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)" || true
          fi
          rm -rf ~/miniconda* ~/anaconda* ~/.conda ~/.condarc || true
          rm -rf "/Applications/Visual Studio Code.app" || true
          rm -rf ~/.vscode* || true

      - name: Run First Year Orchestrator
        env:
          REMOTE_PS: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name || github.repository }}
          BRANCH_PS: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref_name }}
        run: |
          echo "Testing First Year Orchestrator from: $REMOTE_PS/$BRANCH_PS"
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/$REMOTE_PS/$BRANCH_PS/MacOS/Components/orchestrators/first_year_students.sh)"

      - name: Verify Installation
        run: |
          # Source environment
          source ~/.bashrc || true
          
          # Verify conda
          which conda
          conda --version
          conda info --base
          
          # Verify VS Code
          code --version
          
          # Verify Python version
          EXPECTED_VERSION="${{ env.PYTHON_VERSION_PS }}"
          INSTALLED_VERSION=$(python3 --version | cut -d " " -f 2)
          if [[ "$INSTALLED_VERSION" != "$EXPECTED_VERSION"* ]]; then
            echo "Installed Python version ($INSTALLED_VERSION) does not match expected version ($EXPECTED_VERSION)"
            exit 1
          fi
          
          # Verify first-year packages
          python3 -c "import dtumathtools, pandas, scipy, statsmodels, uncertainties; print('All first-year packages imported successfully')"
          
          # Verify VSCode extensions
          code --list-extensions | grep -i python || { echo "Python extension not found"; exit 1; }
          
          echo "First Year Orchestrator verification completed successfully"