name: Test Constructor Working

on:
  workflow_dispatch:
  pull_request:
    branches:
      - constructor-pkg-installer
    paths:
      - 'MacOS/constructor_installer/**'
      - '.github/workflows/test-constructor-working.yml'

env:
  PYTHON_VERSION_PS: "3.11"

jobs:
  test-constructor:
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ env.PYTHON_VERSION_PS }}
          channels: conda-forge
          channel-priority: strict
          auto-activate-base: true

      - name: Install Constructor
        shell: bash -l {0}
        run: |
          conda install -c conda-forge constructor -y
          constructor --version

      - name: Build PKG
        shell: bash -l {0}
        working-directory: MacOS/constructor_installer/python_stack
        run: |
          echo "=== Building Constructor PKG ==="
          ./build.sh

      - name: Install and Test PKG
        shell: bash -l {0}
        working-directory: MacOS/constructor_installer/python_stack
        run: |
          echo "=== Testing PKG ==="
          PKG_FILE=$(find builds/ . -name "*.pkg" -type f 2>/dev/null | head -1)
          if [[ -n "$PKG_FILE" ]]; then
            echo "Found PKG: $PKG_FILE"
            installer -pkginfo -pkg "$PKG_FILE"
            echo "PKG build successful!"
          else
            echo "❌ No PKG file found"
            exit 1
          fi